### NumPy的安装和创建

In [14]:
# pip install numpy

导入NumPy库

In [15]:
import numpy as np

创建一维数组

In [16]:
arr1 = np.array([1,2,3])

创建二维数组

In [17]:
arr2=np.array([[1,2,3],[4,5,6]])

总结 有几个[ ]括号就是几维数组  
如果传入非同类数组 会自动强制转化为同类行

### 常用命令

In [ ]:
# 维度
print(arr1.ndim)# 1 一维数组
print(arr2.ndim)# 2 二维数组


In [ ]:
# 维度和元素
print(arr1.shape)#(3,)一组三个元素
print(arr2.shape)#(2, 3)二组三个元素

In [ ]:
# 元素总个数
print(arr1.size)# 3
print(arr2.size)# 6

In [ ]:
# 元素类型
print(arr1.dtype)# int64

### 直接创建方法

In [ ]:
np.zeros(3)#不用赋值给变量
#array([0., 0., 0.])
#有小数点代表是浮点数

In [ ]:
np.ones(5)#不用赋值给变量
#array([1., 1., 1., 1., 1.])
#有小数点代表是浮点数

In [ ]:
np.arange(2,10,2)#起始值，终止值，步长
# array([2, 4, 6, 8])